[phases.setup]
nixPkgs = ['php84', 'php84Packages.composer', 'php84Extensions.pdo', 'php84Extensions.pdo_mysql', 'php84Extensions.mbstring', 'php84Extensions.tokenizer', 'php84Extensions.xml', 'php84Extensions.ctype', 'php84Extensions.fileinfo', 'php84Extensions.openssl', 'php84Extensions.gd', 'php84Extensions.curl', 'php84Extensions.zip', 'php84Extensions.bcmath', 'nodejs_22']

[phases.install]
cmds = [
  'cp .env.example .env',
  'composer install --no-dev --optimize-autoloader --no-interaction',
  'npm ci'
]

[phases.build]
cmds = [
  'npm run build'
]

[variables]
NIXPACKS_PHP_ROOT_DIR = "/app/public"
NIXPACKS_PHP_FALLBACK_PATH = "/index.php"

